#!/bin/sh

script_dir=$(realpath $(dirname $0))
: "${WUMBO_PATH:="$script_dir/build/wasm32-emscripten-clang/Release/wumbo.mjs"}"
export WUMBO_PATH
: "${WUMBO_INIT_PATH="$script_dir/index.mjs"}"
node --experimental-wasm-jspi "$WUMBO_INIT_PATH" "$@"

